# Generated by Django 4.0.7 on 2022-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleId', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleName', models.CharField(max_length=500)),
            ],
        ),
    ]
