# Generated by Django 4.0.7 on 2022-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleAuthor',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleContent',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleCreatedAt',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleName',
            field=models.CharField(max_length=100),
        ),
    ]
