# Generated by Django 4.0.7 on 2022-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0003_alter_article_articlecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleContent',
            field=models.CharField(max_length=10000),
        ),
    ]
